# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev r-cran-ncdf4 libudunits2-dev
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_github(c('yihui/tinytex', 'rstudio/rmarkdown'))"
  - R -e "tinytex::install_tinytex()"